name: test
on: [ push ]
jobs:
  test:
    runs-on: ubuntu-20.04
    env:
      DB_DATABASE: test_db
      DB_USER: root
      DB_PASSWORD: root
    steps:
      - uses: actions/checkout@v3
      - name: mysql
        working-directory: ./.github/workflows/
        run: |
          sudo systemctl start mysql.service
          mysql -e 'CREATE DATABASE ${{ env.DB_DATABASE }};' -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }}
          mysql -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }} ${{ env.DB_DATABASE }} < test-data/test-database.mysql
      - name: cpan
        working-directory: ./.github/workflows/
        run: |
          sudo apt-get install libdbd-mysql-perl
      - name: verifymysql
        working-directory: ./.github/workflows/
        run: |
          ./test-data/script-verify-database-data.pl


