name: test
on: [ push ]
jobs:
  test:
    runs-on: ubuntu-20.04
    env:
      DB_DATABASE: test_db
      DB_USER: root
      DB_PASSWORD: root
    steps:
      - run: |
          sudo systemctl start mysql.service
          mysql -e 'CREATE DATABASE ${{ env.DB_DATABASE }};' -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }}

